# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('retiresmartz', '0026_auto_20170301_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_401a',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_401k',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_403b',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_403k',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_409a',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_457',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_esop',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_gov',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_ind_401k',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_ind_roth_401k',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_ira',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_mon_purch',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_pay_deduct_ira',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_priv_457',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_prof_sharing',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_qual_annuity',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_qual_np',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_qual_np_roth',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_roth_401k',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_roth_ira',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_sarsep_ira',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_sep_ira',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_simple_ira',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='accounts_tax_def_annuity',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_401a',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_401k',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_403b',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_403k',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_409a',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_457',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_esop',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_gov',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_ind_401k',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_ind_roth_401k',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_ira',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_mon_purch',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_pay_deduct_ira',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_priv_457',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_prof_sharing',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_qual_annuity',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_qual_np',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_qual_np_roth',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_roth_401k',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_roth_ira',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_sarsep_ira',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_sep_ira',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_simple_ira',
        ),
        migrations.RemoveField(
            model_name='retirementprojection',
            name='part_accounts_tax_def_annuity',
        ),
        migrations.AddField(
            model_name='retirementprojection',
            name='list_of_account_balances',
            field=jsonfield.fields.JSONField(help_text='List of annual accounts', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='retirementprojection',
            name='part_list_of_account_balances',
            field=jsonfield.fields.JSONField(help_text='List of annual accounts', null=True, blank=True),
        ),
    ]
